### ISSUE TITLE
Tag version 1.6.2

### ISSUE THREAD

**Issue by wxmerkt** [stack-of-tasks/eigenpy#100]
Can we tag the current master as 1.6.2 please? I'd like to make a release to the ROS buildfarm with the latest fixes and also change it to a proper third-party library, subsequently fixing now dependent packages (e.g. MoveIt) and get the package ready for the MEMMO deliverable.

**Comment by jcarpent** [comment]
This is now done. @wxmerkt Sorry for the delay.

**Comment by wxmerkt** [comment]
Thank you! :-)
