### ISSUE TITLE
robotpkg eigenpy binary does not depend on libeigen3-dev

### ISSUE THREAD

**Issue by wxmerkt** [stack-of-tasks/eigenpy#112]
I am setting up a new CI system and realised that installing `robotpkg-py27-eigenpy` does not install `libeigen3-dev` (i.e. does not depend on it).

Here is the output of `dpkg`:
```
$ dpkg -s robotpkg-py27-eigenpy
Package: robotpkg-py27-eigenpy
Status: install ok installed
Priority: extra
Section: robotpkg/math
Maintainer: hpp@laas.fr
Architecture: amd64
Source: /opt/robotpkg/var/lib/robotpkg/packages/bsd/Ubuntu-16.04-x86_64/pub/py27-eigenpy-1.6.1.tgz
Version: 1.6.1
Replaces: robotpkg-py27-eigenpy
Provides: robotpkg-py27-eigenpy
Depends: libboost-python1.58-dev (>= 1.34.1), libboost-python1.58.0 (>= 1.34.1), libstdc++6 | libstdc++6, python-numpy (>= 1:1), python2.7-minimal (>= 2.7), python2.7-minimal (<< 2.8), libpython2.7-dev (>= 2.7), libpython2.7-dev (<< 2.8)
Conflicts: robotpkg-py35-eigenpy (= 1.4.5), robotpkg-py27-eigenpy (= 1.4.3), robotpkg-py35-eigenpy (= 1.4.1r1), robotpkg-py27-eigenpy (= 1.4.1), robotpkg-py27-eigenpy (= 1.4.1r1), robotpkg-py35-eigenpy (= 1.4.1), robotpkg-py27-eigenpy (= 1.6.0), robotpkg-py27-eigenpy (= 1.6.1), robotpkg-py27-eigenpy (= 1.4.4), robotpkg-py35-eigenpy (= 1.4.4), robotpkg-py35-eigenpy (= 1.4.3), robotpkg-py35-eigenpy (= 1.6.1), robotpkg-py35-eigenpy (= 1.4.2), robotpkg-py35-eigenpy (= 1.6.0), robotpkg-py35-eigenpy (= 1.5.1), robotpkg-py27-eigenpy (= 1.4.5), robotpkg-py35-eigenpy (= 1.5.0), robotpkg-py27-eigenpy (= 1.5.0), robotpkg-py35-eigenpy (= 1.4.2r1), robotpkg-py27-eigenpy (= 1.5.1), robotpkg-py35-eigenpy (= 1.4.1r2), robotpkg-py27-eigenpy (= 1.4.2r1), robotpkg-py27-eigenpy (= 1.4.1r2), robotpkg-py27-eigenpy (= 1.4.2), robotpkg-eigenpy (= 1.3.0), robotpkg-eigenpy (= 1.3.2), robotpkg-eigenpy (= 1.3.3), robotpkg-eigenpy (= 1.3.1r1), robotpkg-eigenpy (= 1.4.0), robotpkg-eigenpy (= 1.3.0r1), robotpkg-eigenpy (= 1.4.0r2), robotpkg-eigenpy (= 1.3.1), robotpkg-eigenpy (= 1.4.0r1), robotpkg-py27-eigenpy
Description: Eigen bindings to python
 License: 2-clause-bsd
 Debian-Packager: robotpkg@laas.fr
 Bindings between numpy and eigen using boost::python
 .
 Homepage:
 https://github.com/stack-of-tasks/eigenpy
Homepage: https://github.com/stack-of-tasks/eigenp
```

I think it should have the dependency to install `libeigen3-dev` as it includes headers that depend on it. What do you think? @jcarpent @nim65s

**Comment by jcarpent** [comment]
You're totally right. @nim65s Could you discuss this issue with Anthony (in charge of robotpkg)?

**Comment by jcarpent** [comment]
Thanks a lot @wxmerkt for raising this issue!

**Comment by nim65s** [comment]
Hi @wxmerkt , and thanks for this question.

As Eigen is header only, eigenpy.so is not linked to it.
And about the headers: do we really leak Eigen headers inside eigenpy's public headers ? And if so, shouldn't we avoid that ?

Anyway, I think we should be able to use eigenpy on a system where libeigen3-dev is not installed, as, from my understanding, all those lib*-dev packages are only necessary to compile things, and never required runtime dependencies, right ?

Then, we could even split the binary packages into eigenpy (with the .so) and libeigenpy-dev (with the headers), and this way, we could even install libeigenpy-dev along py27-eigenpy & py36-eigenpy, which would be a nice thing to have, if we had time for this. Right now, py27-eigenpy & py36-eigenpy are conflicting, because they are both installing the same headers at the same place.

Our ultimate goal is always to embed stuff on robots, so avoiding non required dependencies is always a good idea :)

**Comment by jcarpent** [comment]
@nim65s It makes sense. @wxmerkt Do you share the same opinion?

**Comment by wxmerkt** [comment]
Hi @nim65s,
The headers installed by eigenpy require Eigen headers internally. As thus the dependency is warranted. 

Introducing a `libeigenpy-dev` and a runtime eigenpy introduces extra maintenance effort required to maintain both packages.

> Our ultimate goal is always to embed stuff on robots, so avoiding non required dependencies is always a good idea :)

How much "extra space" are the `libeigen3-dev` really taking? I don't think this justifies all the extra effort to maintain two packages.

> Right now, py27-eigenpy & py36-eigenpy are conflicting, because they are both installing the same headers at the same place.

Yes, this is a problem indeed. Howevever, the headers shouldn't be different between the two versions. This is also why you have the "conflicts" rule in the debian so it shouldn't happen on a system.

I think the easiest solution is to add the `libeigen3-dev` dependency (and I just spent a lot of time fixing eigenpy issues that wasn't spent on research!).

Thanks,
Wolf

**Comment by jmirabel** [comment]
> Anyway, I think we should be able to use eigenpy on a system where libeigen3-dev is not installed, as, from my understanding, all those lib*-dev packages are only necessary to compile things, and never required runtime dependencies, right ?

@nim65s cannot you declare the dependency only for Ubuntu ?

**Comment by wxmerkt** [comment]
> @nim65s cannot you declare the dependency only for Ubuntu ?

Why would you make it only for Ubuntu? If the package installs headers that depend on Eigen / libeigen3-dev, it should have the dependency. The suggestions appear to be either:

1. Add the `libeigen3-dev` dependency in the debian package.
2. Split eigenpy into two debians: one with runtime, one with headers. 

Given the minimal "overhead" of installing libeigen3-dev and avoiding users (e.g. pinocchio) to depend on both `eigenpy` and `libeigenpy-dev` and the development/maintenance overhead, I'd suggest going with (1).

**Comment by jcarpent** [comment]
I share the same opinion as @wxmerkt. Just adding libeigen3-dev as a required apt dependency for all the packages that depend on it inside robotpkg is the right solution, both in terms of manpower and efficiency.

**Comment by jmirabel** [comment]
@wxmerkt I am fine with Debian. I meant *wherever libeigen3-dev exists*. 1 is a good option. 2 is a bad idea.

**Comment by nim65s** [comment]
Ok, let's do this :)

**Comment by jcarpent** [comment]
@nim65s Do you have an idea for the deployment of such an action?

**Comment by nim65s** [comment]
not yet, I'll work on it today, together with a more general "dependency's dependencies" issue in my packages on robotpkg

**Comment by jcarpent** [comment]
@nim65s What is the status?

**Comment by nim65s** [comment]
I opened a PR for this, and it is still open as it needs some rework. I'll probably need one more month.

**Comment by jcarpent** [comment]
@nim65s Any update on it?

**Comment by nim65s** [comment]
It works now :)

**Comment by jcarpent** [comment]
Very nice. Thanks @nim65s!
