### ISSUE TITLE
How to check whether eigenpy is using array or matrix?

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/eigenpy#117]
Sometimes, it might be useful to verify whether eigenpy is configured to convert Eigen objects to a numpy matrix or array. However, I cannot find a way to do it cleanly, particularly in Python.

I guess I can create a random Eigen object and check its type, but it would not be nice.

Is there a better way? If not, could you add a function such as `isUsingNumpyArray` or `isUsingNumpyMatrix`?

**Comment by jcarpent** [comment]
@gabrielebndn I proposed a solution to your issue here: #118 Is it fine for you?

**Comment by gabrielebndn** [comment]
@jcarpent, it looks perfect, thanks!

**Comment by jcarpent** [comment]
Solved by #118
