### ISSUE TITLE
Inconsistent numpy array shape for return and parameter type ?

### ISSUE THREAD

**Issue by pFernbach** [stack-of-tasks/eigenpy#126]
I'm not sure if I'm doing something wrong or if it's a real issue in eigenpy.
I am using the same C++ type (an `Eigen::VectorXd`) for the return type and the parameter type of a binded method. 
It is working well with Numpy matrix but when using `eigenpy.switchToNumpyArray()` the returned array is of shape `(x,)` while the array given as parameter must be of shape `(x,1)`
Right now I need to add `.reshape(-1,1)` to all the arrays given as input to this kind of methods. 

Is there something specific to define when doing the c++ binding such that the method can take array of shape `(x,)` as parameters ?

**Comment by jcarpent** [comment]
I think you should have a look to the devel branch which has a fix for you.

**Comment by pFernbach** [comment]
Thanks, my issue is solved in the devel branch. I'll wait for a binary release of this changes to remove all the `reshape` currently needed in my package.
