### ISSUE TITLE
Release 1.6.8 did not update package.xml version

### ISSUE THREAD

**Issue by wxmerkt** [stack-of-tasks/eigenpy#127]

**Comment by jcarpent** [comment]
Do you need a new release or the commit is enough?

**Comment by wxmerkt** [comment]
I'd need a new tag so I can release it to the buildfarm (along with Pinocchio 2.2.0). Sorry for the inconvenience

**Comment by jcarpent** [comment]
I've just removed tag 1.6.9 and I will update a new release with a fix.

**Comment by wxmerkt** [comment]
Thank you, Justin!
