### ISSUE TITLE
Fatal assert when exposing a matrix 1x1

### ISSUE THREAD

**Issue by nmansard** [stack-of-tasks/eigenpy#144]
I encounter a fatal assert (when using EigenPy in Pinocchio) when exposing a matrix of shape [1,1]. With a more precise context, I have a mass matrix for a 1-dof (pendulum) system in data.M that has a shape [1,1]. When accessing this matrix, I get an assert in debug mode, and a segfault (or various memory failure) in release mode. 

Here is the copy of the assert:
python3: /eigenpy-1.6.13/include/eigenpy/map.hpp:44: static eigenpy::MapNumpyTraits<MatType, InputScalar, 0>::EigenMap eigenpy::MapNumpyTraits<MatType, InputScalar, 0>::mapImpl(PyArrayObject*) [with MatType = Eigen::Matrix<double, -1, -1>; InputScalar = double; eigenpy::MapNumpyTraits<MatType, InputScalar, 0>::EigenMap = Eigen::Map<Eigen::Matrix<double, -1, -1>, 0, Eigen::Stride<-1, -1> >; typename eigenpy::StrideType<PlainObjectTypeT>::type = Eigen::Stride<-1, -1>; PyArrayObject = tagPyArrayObject]: Assertion `PyArray_NDIM(pyArray) == 2' failed.

@nim65s prepared a docker to study the bug. Could you copy the instruction to run it? Many thanks for your help.

**Comment by nim65s** [comment]
Hi,

I was able to reproduce this bug using Python 3 on 16.04. I wasn't with Python 2, and on 18.04, this bug was appearing only if hpp-fcl's binding were not installed.

Here is a [Dockerfile](https://github.com/nim65s/gepetto-utils/blob/master/docker/pinocchio/Dockerfile.nolts). I pushed an image with it at `gepetto/utils:pinocchio-16.04-py3-debug` on docker hub.

You can run `docker run --rm -it gepetto/utils:pinocchio-16.04-py3-debug` to get it, and then use this script, provided by @nmansard:

```python
import numpy as np
import pinocchio as pio
pio.switchToNumpyArray()

def createPendulum():
    '''
    Creates the Pinocchio kinematic <rmodel> model for 1-pendulum
    '''
    rmodel = pio.Model()
    
    inertia = pio.Inertia(1.,
                          np.array([0.0,0.0,.5]),
                          1./5*np.diagflat([ 1e-2,1,  1e-2 ]) )
    print(inertia)
    jointId = rmodel.addJoint(0,pio.JointModelRY(),pio.SE3.Identity(),"joint0")
    rmodel.appendBodyToJoint(jointId,inertia,pio.SE3.Identity())

    return rmodel

rmodel= createPendulum()
rdata = rmodel.createData()
print(rdata.M)
print(rdata.M)
print(rdata.M)
```

**Comment by jcarpent** [comment]
First, the issue seems to be related to the Eigen version or/and the Python version. With Eigen 3.3.7, I don't have any issue. I've just opened #147. Can you check it on your side.

**Comment by jcarpent** [comment]
Solved by #147.

**Comment by jcarpent** [comment]
No feedbacks @nmansard?!

**Comment by jcarpent** [comment]
No feedbacks @nmansard?!
