### ISSUE TITLE
Scope of switchToNumpyXXX

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/eigenpy#146]
The following two scripts

`a.py`:
```py
import eigenpy
eigenpy.switchToNumpyArray()
```

`b.py`:
```py
import eigenpy
import a
print(eigenpy.getNumpyType()) # prints <class 'numpy.ndarray'>
```

Demonstrate that eigenpy's return type is a _global_ setting which affects importing modules (I have no idea how it would act in a multi-threaded case, it would be interesting to know it).

This is displeasing, because it forces to either switch all of the codebase at once or to put a lot of pre-emptive `switchToNumpyXXX` just to play on the safe side and be sure that the setting was not changed by another module.

I don't know whether it is doable or whether you agree with me, but would it be possible to limit the scope of `switchToNumpyXXX` to the module where it is invoked?

**Comment by nim65s** [comment]
Hi,

When you type `import a`, python will go through `a`, and therefore will execute this `eigenpy.switchToNumpyArray()`.

**Comment by nim65s** [comment]
```python
# a.py
import eigenpy


def toto():
    eigenpy.switchToNumpyArray()
    print(eigenpy.getNumpyType())  # prints <class 'numpy.ndarray'>

# b.py
import eigenpy

import a

print(eigenpy.getNumpyType())  # prints <class 'numpy.ndarray'>

a.toto()
```
Will print:
```
<class 'numpy.matrixlib.defmatrix.matrix'>
<class 'numpy.ndarray'>
```

**Comment by gabrielebndn** [comment]
> When you type `import a`, python will go through `a`, and therefore will execute this `eigenpy.switchToNumpyArray()`.

Yes, of course, that was clear to me.
What I am wondering is: is there a way to make it so that `switchToNumpyArray()` only has an effect in a certain module?

**Comment by jcarpent** [comment]
The answer is NO. It is not possible in the way Boost.Python works to change the converter for a given type. There is only one converter for each type.

What can be done, it is to register a specific converte for a function return type. But this should be done for a whole module like Pinocchio. I don't want to waist my time on it.

**Comment by gabrielebndn** [comment]
> The answer is NO. It is not possible in the way Boost.Python works to change the converter for a given type. There is only one converter for each type.
> 
> What can be done, it is to register a specific converte for a function return type. But this should be done for a whole module like Pinocchio. I don't want to waist my time on it.

Mmmm, ok... Do you have any idea what would happen in a multi-threaded setting? If one thread calls `switchToNumpyXXX`, will this change the return type of the other threads right in the middle of the execution?

**Comment by jcarpent** [comment]
Yes!

**Comment by gabrielebndn** [comment]
Oooh, that might be *bad*.
Ok. Take-home message: **all of your codebase should consistently employ either matrix or array**. End of the story. Thanks for the clarifications
