### ISSUE TITLE
Revert CMake modules update and make hotfix release

### ISSUE THREAD

**Issue by wxmerkt** [stack-of-tasks/eigenpy#157]
Cf. https://github.com/jrl-umi3218/jrl-cmakemodules/issues/324

The current master does not work on a freshly installed 18.04 due to the upstream changes in `python.cmake`. Can we please revert the sync of the cmake submodule and make a patch release?

**Comment by jcarpent** [comment]
I will directly fix the issue in the module if you don't mind. Is it fine for you?

**Comment by wxmerkt** [comment]
Yes, absolutely :-)

**Comment by jcarpent** [comment]
@wxmerkt I'm waiting for #159 to provide a new release.

**Comment by jcarpent** [comment]
Release done!
