### ISSUE TITLE
find_package(eigenpy REQUIRED) does not populate eigenpy_INCLUDE_DIRS

### ISSUE THREAD

**Issue by wxmerkt** [stack-of-tasks/eigenpy#174]
This is the source for the breakage between 1.6.9 and 2.1.2 that prevents updating the ROS release.

To reproduce (with latest devel):
```cmake
find_package(eigenpy REQUIRED)
message(WARNING ${eigenpy_INCLUDE_DIRS})
```
This prints an empty message.

**Comment by jcarpent** [comment]
Fixed by #175.
