### ISSUE TITLE
Minor issue with Python unit test on MacOS 13

### ISSUE THREAD

**Issue by zongmianli** [stack-of-tasks/eigenpy#18]
Hello, I have got an argument mismatch error when trying to run `python/test_unit/test_eigenpy.py`:

> ArgumentError: Python argument types in
>     matrix.reflex()
> did not match C++ signature:
>     reflex(Eigen::Matrix<double, -1, -1, 0, -1, -1>, bool)

Specifically, this error occurred when the program was passing a numpy Matrix `M` to the function`eigenpy.reflex(M,verbose)` . However the problem can be solved by replacing 
`const typename eigenpy::UnalignedEquivalent<MatType>::type & M` with `const Eigen::MatrixXd & M` (i.e. specifying the argument type). There should be a bug in the Template definition.

**Comment by jcarpent** [comment]
This code is deprecated. I advise you to not use it as it is now.
It was used before when alignment of matrices was an issue. This is no more the case.
