### ISSUE TITLE
Release eigenpy into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [stack-of-tasks/eigenpy#188]
Would you mind releasing `eigenpy` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 41 repos need it.

I'm not sure how much work it will need. There is a [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/).  The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) may have other changes this repo needs.

**Comment by wxmerkt** [comment]
Hi @sloretz,
I'll work on this and already made the first PR to migrate earlier today (#187).

**Comment by jcarpent** [comment]
Do you need a new release?

**Comment by wxmerkt** [comment]
Yes, please. I just dropped you an email regarding that. :-)

**Comment by jcarpent** [comment]
I'm done with the release. I let @wxmerkt manage this issue.

**Comment by wxmerkt** [comment]
Release is out: https://github.com/ros/rosdistro/pull/24548

I'll leave the issue open until we know it passed the buildfarm.

**Comment by wxmerkt** [comment]
Failure on Debian Buster is due to issue in detecting NumPy in the jrl-cmake-modules, cf. https://github.com/jrl-umi3218/jrl-cmakemodules/issues/373

**Comment by wxmerkt** [comment]
We are still fighting memory exhaustion on the buildfarm when exposing the different Scalar types. I hope this will pass in stages over the next few days when it starves other jobs of their memory. Otherwise we can close this issue @jcarpent.

**Comment by jcarpent** [comment]
Thanks for the report @wxmerkt and the fixes.
Thanks @sloretz for reporting this issue.
