### ISSUE TITLE
Error when including `eigenpy.hpp`

### ISSUE THREAD

**Issue by acxz** [stack-of-tasks/eigenpy#195]
```
In file included from /usr/include/eigenpy/fwd.hpp:14,
                 from /usr/include/eigenpy/eigenpy.hpp:9,
                 from /home/acxz/vcs/git/github/ros-noetic-arch/ros-noetic-moveit-ros-planning-interface/src/moveit-1.0.3/moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp:53:
/usr/include/eigenpy/numpy.hpp:15:10: fatal error: numpy/numpyconfig.h: No such file or directory
   15 | #include <numpy/numpyconfig.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by wxmerkt** [comment]
Hi @acxz,
I see you are compiling this for MoveIt on Arch using the Noetic release. I haven't tested either yet (and MoveIt hasn't been tested or released on Noetic). Can you please check whether numpy-dev is available and whether you can locate that header? (Or provide a docker to reproduce?)

Note: MoveIt is not yet using CMake targets but pkg-config.

**Comment by acxz** [comment]
Hello @wxmerkt thx for responding

Just found out that there is a `ros-noetic-eigenpy` package that you are maintaining at https://github.com/ipab-slmc/eigenpy_catkin-release so I'm trying to build that package right now and use that as a dep instead of this repo. I'll let you know how it goes.

As for numpy headers I do have those installed.

**Comment by wxmerkt** [comment]
@acxz: The release has a few patches applied on top of this repository for noetic to fix some CMake module issues, cf. https://github.com/ipab-slmc/eigenpy_catkin-release/tree/patches/release/noetic/eigenpy

Any questions, please let me know

**Comment by acxz** [comment]
Is there any reason why these patches are not merged into this repository?

**Comment by nim65s** [comment]
@acxz : on Arch, you can use directly https://aur.archlinux.org/packages/eigenpy/

**Comment by acxz** [comment]
Hey @nim65s! Thx for responding

That is actually how I got theerror. So I was like hey maybe I should use the catkin package, but then looking at the latest moveit release they are using the system eigenpy, which does not work. It does however work with pkgconfig instead of find_package.

**Comment by acxz** [comment]
The above mentioned PR resolves the issue for me. From what I understand, `find_package` does not properly work with eigenpy (might be some bug in eigenpy's CMakeLists.txt) so for me to use eigenpy in downstream packages I need to use its `pkgconfig` which resolved the issue for me for `moveit-ros-planning-interface`.

I'll keep this issue open since it seems like this points to a deeper issue in eigenpy's CMake configuration.

**Comment by jcarpent** [comment]
The cmake packaging of EigenPy is working and it is tested on the CI. Could you provide a tiny example to allow to reproduce it?

**Comment by acxz** [comment]
@jcarpent sounds good, yeah maybe I am messing up somewhere locally on my end.

**Comment by nim65s** [comment]
I see. And I also saw your https://aur.archlinux.org/cgit/aur.git/tree/eigenpy.patch?h=ros-melodic-moveit-ros-planning-interface 

I think the issue is in `moveit_ros/planning_interface/move_group_interface/CMakeLists.txt` that compiles `moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp` under the `${MOVEIT_LIB_NAME}_python` target name on line 8.

**Comment by acxz** [comment]
Just tried and it works, I think it is safe to close this since the issue is in the moveit repo.
Sorry for blaming the cmake packaging of eigenpy ... 

Thx for quick response and the amazing software!

**Comment by wxmerkt** [comment]
To clarify: The EigenPy packaged via ROS is the EigenPy in this repository, plus the fixes to the cmake module linked above. MoveIt uses EigenPy via ROS that includes these fixes. We spent a long time (a process that took weeks and coordination) to ensure backward compatibility when the PkgConfig/CMake packaging changed, so it should all still work. My latest checks on Melodic work, and so does the CI that tests these. I will follow up on the MoveIt PR.
