### ISSUE TITLE
on robotpkg, eigenpy library should have soversion

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/eigenpy#200]
Maybe on robotpkg, eigenpy library should be suffixed with the version number. @nim65s can you handle it ?

For pinocchio, we may do the same thing although it isn't as problematic right now (but may become in the future).

_Originally posted by @jmirabel in https://github.com/stack-of-tasks/pinocchio/issues/1229#issuecomment-653026773_

**Comment by jcarpent** [comment]
Solved by #201.
