### ISSUE TITLE
build fails in archlinux

### ISSUE THREAD

**Issue by oarriaga** [stack-of-tasks/eigenpy#206]
Hi, I am trying build pinocchio from AUR but whenever it tries to build eigenpy I encounter the following error:
```
 -- Found Python3: /sbin/python (found version "3.8.5") found components: Interpreter Development Development.Module Development.Embed 
-- PythonLibraryDirs: /usr/lib
-- PythonLibVersionString: 3.8.5
-- Python site lib: lib/python3.8/site-packages
-- checking for numpy
--  NUMPY_INCLUDE_DIRS=/usr/lib/python3.8/site-packages/numpy/core/include
-- Found Boost: /lib64/cmake/Boost-1.72.0/BoostConfig.cmake (found version "1.72.0")  
CMake Error at cmake/boost.cmake:71 (STRING):
  STRING sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:70 (SEARCH_FOR_BOOST)


CMake Error at cmake/boost.cmake:278 (GET_FILENAME_COMPONENT):
  GET_FILENAME_COMPONENT called with incorrect number of arguments
Call Stack (most recent call first):
  CMakeLists.txt:218 (PKG_CONFIG_APPEND_BOOST_LIBS)


-- Configuring incomplete, errors occurred!
See also "/home/xxxxx/.cache/yay/eigenpy/src/eigenpy-2.4.3/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
    Aborting...
error making: %!s(func() string=0x55a3e1cfe410)
```
It seems have found Boost  and python3.8 so I don't know if it may be an incorrect syntax in the CMake file. Thanks!

**Comment by nim65s** [comment]
Hi @oarriaga,
Just to be sure: are you building the latest release, or eigenpy-git ?

**Comment by nim65s** [comment]
I can't reproduce your issue on a clean container, with `base-devel`, `git` and `yay-bin`, running `yay -Syu --noconfirm eigenpy`, so I guess something comes from your side.

**Comment by nim65s** [comment]
I'd say that CMake finds `boost`, but not `boost-libs`, because on  `cmake/boost.cmake:71`, it looks like  `Boost_LIB_VERSION` is not defined correctly in your case. But `boost-libs` is correctly defined as a dependency in `eigenpy/PKGBUILD`.

**Comment by jcarpent** [comment]
@oarriaga Which version of CMake are you using?

**Comment by oarriaga** [comment]
Thanks for the fast responses :-)
I am installing `eigenpy` by:

```
yay -S eigenpy
```

My cmake version is:

```
cmake --version
cmake version 3.18.1

```

**Comment by oarriaga** [comment]
Hi, yes you were right it was not finding boost-libs but it was installed. 

I found [this ](https://bugs.archlinux.org/task/64132)and it seems like my PATH variable was confusing CMake for the actual path for boost, but now It's building.

Thanks :-)
