### ISSUE TITLE
Writing to subsets of vectors fails silently

### ISSUE THREAD

**Issue by wxmerkt** [stack-of-tasks/eigenpy#210]
This issue could stem from Boost.Python but I am wondering if there is a way to make this more transparent rather than silently fail.

**What's happening**
I am trying to modify a subset of a vector. Often these are exposed as properties using get_vector, set_vector (with or without Eigen::Ref). Say, I have a Nd-vector and now I want to modify only a subset e.g. `vector[0:3] = 3.`. This operation will succeed (i.e., no exception in Python) but the vector itself won't have changed. I can set the entire vector though and the content will change.

**What I expect to happen**
1. Either the subset of the vector changes. This might require the use of `Eigen::Ref` I presume?
2. Or, I get an exception that this operation won't work or that I am passing the wrong length.

**Example**
1. In Crocoddyl, `u_lb` is exposed using `get_u_lb` and `set_u_lb` (cf. [here](https://github.com/loco-3d/crocoddyl/blob/c31a27432f9f2b365faec31b5e7cb37d90b7abb0/bindings/python/crocoddyl/core/action-base.cpp#L86-L87)). `set_u_lb` has a check that the vector passed in has the correct size and otherwise throws to avoid messing up memory (cf. [here](https://github.com/loco-3d/crocoddyl/blob/4708428676f596f93ffe2df739faeb5cc38d2326/include/crocoddyl/core/action-base.hxx#L121-L129)). Calling `model.u_lb[0:2] = 1.` or similar silently _passes_ but does not modify the content. Calling `model.u_lb = 123. * np.ones(model.nu)` works as intended as we are passing a vector of the correct size.
2. In Pinocchio, e.g. using a SE(3) to modify the translation:
```python
import pinocchio
a = pinocchio.SE3()
print("Before:", a.translation)  # [0,0,0]
a.translation[0] = 1.  # <-- this operation should either work or throw
print("After 'modifying' one element (x)", a.translation) # [0,0,0]
a.translation = np.ones(3)
print("After modifying the entire vector", a.translation) # [1,1,1]
```

Is there anything that (a) could fix this behaviour or (b) throws on this unsupported assignment?

**Comment by jcarpent** [comment]
Pinocchio does not have the feature activated already. We may switch now. @wxmerkt what do you think?

**Comment by jmirabel** [comment]
> Pinocchio does not have the feature activated already.

Does this mean the feature exists but isn't used ?

**Comment by wxmerkt** [comment]
Being able to use the indexing would be nice and really user-friendly of course. Would that mean switching to `Eigen::Ref` or to use direct access rather than getter/setter?

My main point is: Can there be a warning/exception when a user tries to write to a subset and it silently fails? It doesn't even trigger the setter - it just does nothing but appears to do something (because no error/warning/exception).

**Comment by jcarpent** [comment]
This means that the feature exists but we are not activating it when building the bindings.

**Comment by jmirabel** [comment]
What is the reason for not activating it ? I agree with @wxmerkt that it is a nice feature. I am regularly annoyed by this issue.

**Comment by jcarpent** [comment]
No apparent reason, just nobody took the time for it. I will handle it.

**Comment by wxmerkt** [comment]
Without activating it, is there a way to have/force an error/exception to trigger when it's not activated? Because without explicitly activating, it fails silently which is a huge "gotcha".

**Comment by jcarpent** [comment]
This feature should be on the side of NumPy, not on the side of Pinocchio/EigenPy. There is no way from our side to mention it.

**Comment by wxmerkt** [comment]
Thanks, makes sense and something to keep in mind

**Comment by jcarpent** [comment]
@wxmerkt @jmirabel I've just realized that a feature was missing for Pinocchio, which was the exposition of Eigen::Ref to Python. 
#211 solves this issue.
After that, we will proceed to a new Release.
