### ISSUE TITLE
dpkg: error processing archive /var/cache/apt/archives/robotpkg-py27-eigenpy_2.6.1_amd64.deb (--unpack):

### ISSUE THREAD

**Issue by heli-sudoo** [stack-of-tasks/eigenpy#222]
I tried install eigenpy using  sudo apt install robotpkg-py27-eigenpy, and I got the following error:

dpkg: error processing archive /var/cache/apt/archives/robotpkg-py27-eigenpy_2.6.1_amd64.deb (--unpack):
 trying to overwrite '/opt/openrobots/include/eigenpy/angle-axis.hpp', which is also in package robotpkg-py36-eigenpy 2.6.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/robotpkg-py27-eigenpy_2.6.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Any help would be appreciated!

**Comment by jcarpent** [comment]
You have already installed robotpkg-py36-eigenpy. You need to uninstall it first.
