### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by mauku** [stack-of-tasks/eigenpy#230]
Hi , 
i have installed the package for python 3.6 with the following command : sudo apt install robotpkg-py36-eigenpy
However , when I try to import eigenpy i get the following error : 
 import eigenpy
  File "/opt/openrobots/lib/python3.6/site-packages/eigenpy/__init__.py", line 17, in <module>
    from .eigenpy import *
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1: undefined symbol: PyClass_Type

It seems its compiled with boost lib for python 2.7 , any suggestions how to solve this ? 
Thanks in advance , Markus !

**Comment by jcarpent** [comment]
Dear @mauku,

You should uninstall eigenpy for Python 2.7.
```
apt-get uninstall robotpkg-py36-eigenpy
```

On a large level, I would recommand to use conda to install eigenpy for easy and robust installation, if you are not confident with your current environment settings.

**Comment by mauku** [comment]
Thanks for the fast answer. I already installed eigenpy for Python 2.7 . The issue stays the same. I would prefer the debian package over conda, since I don't have the best experiences with conda.

**Comment by jcarpent** [comment]
In fact, you should uninstall this package. There is a conflict between eigenpy for Python 2.7 and eigenpy for Python 3.6

**Comment by mauku** [comment]
Sorry i misswrote , i uninstalled the package , but the error stays

**Comment by jcarpent** [comment]
Could you do: `locate libeigen.so`
And also `export LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH`

**Comment by mauku** [comment]
Doesn't find any libeigen.so only libeigenpy.so. But I think I found the issue. There was one libeigenpy.so file from ros melodic eigenpy package for python2. After removing all eigenpy files for ros it seems to work.

**Comment by jcarpent** [comment]
Yes, I meant `libeigenpy.so`

**Comment by wxmerkt** [comment]
> There was one libeigenpy.so file from ros melodic eigenpy package for python2. After removing all eigenpy files for ros it seems to work.

It's important not to mix and match EigenPy from ROS and EigenPy from RobotPkg particularly across different Python versions. It can be worked around by sourcing / setting the paths in the right order but your best bet is to use conda since it will fix the paths for you when activating the environment. Another workaround to removing - since this will break Moveit - would be _not to source ROS by default_

**Comment by mauku** [comment]
Okay thank alot for the answer !Is there a way to use eigenpy for python2 and python3 with still sourcing the ros package path , since I need other ros packages .

**Comment by wxmerkt** [comment]
Right now you cannot use Python 2 and Python 3 simultaneously with the same path variables. You would have to set them per-workspace/console/bash environment - e.g. only source ROS when using ROS - and only set the LD_LIBRARY_PATH and PYTHONPATH for openrobots when using robotpkg's version
