### ISSUE TITLE
Question about bug fix related to Quaternion initialization in Python in Eigenpy2.6.1

### ISSUE THREAD

**Issue by mauku** [stack-of-tasks/eigenpy#234]
Hi,
as mentoined in the title, i would like to ask what are the exact fixes for the bug mentioned in the Eigenpy2.6.1 release , Thanks in advance !

**Comment by jcarpent** [comment]
This is related to https://github.com/stack-of-tasks/eigenpy/commit/61d25345f074e26586147596341c6715a3e7b73c#diff-6140fead50df77449f95d2bd6c41328a2f1d9b05c482f1db69cb6cd3bf3dcb34.
Do you encounter any trouble?

**Comment by mauku** [comment]
Thanks for the fast answer :) 
i am doing 6d pose estimation based on cosypose, which uses the eigenpy 2.6.0 version , I found out that when I use a newer version of eigenpy the estimated 6d poses are not correct anymore , I am not exactly sure why

**Comment by jcarpent** [comment]
Could you provide a tiny example of what happens exactly?

**Comment by mauku** [comment]
Yes i can provide some example images, with estimated poses with Eigenpy 2.6.0  and estimated pose for the same image with eigenpy newer version. for the 2.6.0 version the poses match quite good , but if I use a newer version they are completely wrong. I will upload some example if I have time

**Comment by jcarpent** [comment]
Could you try EigenPy 2.6.3? It is on conda

**Comment by mauku** [comment]
I tried with EigenPy 2.6.3 and 2.6.0 . For 2.6.0 the object poses are correct , but not for 2.6.3.

**Comment by jcarpent** [comment]
Could you just show me where Quaternion are used in CosyPose?
In addition, could you isolate outside of CosyPose the Quaternion operation which leads to troubles?

Otherwise, I won't be able to provide help.

**Comment by jcarpent** [comment]
@mauku Are you sure the bug is coming from EigenPy? Did you update other software?
Again, I would need a minimal example not depending on CosyPose to fix the bug if it exists.
