### ISSUE TITLE
Problem writing C++ binding using eigenpy

### ISSUE THREAD

**Issue by jviereck** [stack-of-tasks/eigenpy#24]
(Not sure filling this here is the correct place - feel free to tell me if there is a mailing list etc that is more suitable.)

Writing a small C++ <--> Python binding, I defined a `hello` function and use `eigenpy` as follows:
```C++
#include <eigenpy/eigenpy.hpp>
#include <boost/python.hpp>

#include <iostream>

void hello(const Eigen::VectorXd & state)
{
   std::cout << "state[0]=" << state[0] << std::endl;
}

namespace bp = boost::python;

BOOST_PYTHON_MODULE(pin_hopper_simulator)
{
    using namespace boost::python;
    eigenpy::enableEigenPy();

    bp::def("hello", hello,
        bp::args("state"),
        "Simple greeting"
      );
}
```

This compiles fine. However, when running the following python code

```python
import toy_hopper_compare.pin_hopper_simulator
import numpy as np

toy_hopper_compare.pin_hopper_simulator.hello(np.matrix([1, 2, 3]))
```

I get the error

```bash
jviereck@rams:toy_hopper_compare$ python test_binding.py
[[1 2 3]]
The internal type as no Eigen equivalent.
Traceback (most recent call last):
  File "test_binding.py", line 10, in <module>
    toy_hopper_compare.pin_hopper_simulator.hello(a)
Boost.Python.ArgumentError: Python argument types in
    toy_hopper_compare.pin_hopper_simulator.hello(matrix)
did not match C++ signature:
    hello(Eigen::Matrix<double, -1, 1, 0, -1, 1> state)
```

Any idea?

**Comment by nmansard** [comment]
Your python code defines an integer vector (only int in 1,2,3, hence interpreted by default by NumPY as np.int type), while your C++ code expects a vector of doubles (VectorXd in argument of the function. The code Python should work find with:
toy_hopper_compare.pin_hopper_simulator.hello(np.matrix([1., 2., 3.]))
Alternatively, explicitly specify that your Python vector is double, by giving the type as second argument of the np.matrix constructor.

It seems difficult to enable the automatic type conversion, and does not follow the philosophy of NumPy in my opinion.

We do not have (yet?) a forum for support, hence posting on the issues seems the only solution, yet suboptimal. This point is often discussed in the team, but nobody yet took the time to propose a solution to this problem.

**Comment by nmansard** [comment]
I close the issue. Feel free to re-open it if needed.

**Comment by jviereck** [comment]
> The code Python should work find with:
> toy_hopper_compare.pin_hopper_simulator.hello(np.matrix([1., 2., 3.]))

Thanks a lot, this made it work :) !
