### ISSUE TITLE
Add support of Eigen::SparseMatrix

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/eigenpy#248]

**Comment by ma-sadeghi** [comment]
Thank you for creating this great package! Can I ask what the status of sparse matrix support is?

**Comment by tomwenseleers** [comment]
Also looking for that! Will support be added in the future?

**Comment by jcarpent** [comment]
Solved via #426

**Comment by jcarpent** [comment]
ping @tomwenseleers @ma-sadeghi
