### ISSUE TITLE
"Correct exception catch" patch from robotpkg

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/eigenpy#25]
There are 2 patches in robotpkg. The first one has been put here by 8771002, and the second one is this:

```
-    PyErr_SetObject(Exception::pyType,boost::python::object(e).ptr());
+    PyErr_SetString(PyExc_RuntimeError, e.what());
```

@jcarpent: could you put it here ? Otherwise I can do it, if you don't have time for that.
The goal is to make a new release, that will be used to move this package from robotpkg-wip to robotpkg.

**Comment by jcarpent** [comment]
I'm going to do it right now.

**Comment by jcarpent** [comment]
I just update devel and master accordingly.
I also push a new release on the ftp server of Robotpkg. 
You can now proceed to the new release.
