### ISSUE TITLE
broken PYTHON_EXPORT_DEPENDENCY

### ISSUE THREAD

**Issue by v4hn** [stack-of-tasks/eigenpy#299]
When I build the current eigenpy master branch or the release tag 2.7.8, the generated cmake config file `lib/cmake/eigenpy/eigenpyConfig.cmake` includes the following lines in that order:

```
...
FINDPYTHON()
....
include("${CMAKE_CURRENT_LIST_DIR}/python.cmake")
```

where the first one is expanded from the variable `@PYTHON_EXPORT_DEPENDENCY_MACRO@` and the latter from `@PACKAGE_EXTRA_MACROS@`. Obviously these two are the wrong way around and as a result the build of my package which depends on `eigenpy` breaks because `FINDPYTHON` does not exist.
I see the same result on a standard Ubuntu 20.04 and a current Lunar-Linux.

Interestingly though the current binaries for 2.7.8 released into https://github.com/ros/rosdistro/pull/33942 do not contain these lines and thus do not trigger this particular error. What am I doing wrong?

**Comment by nim65s** [comment]
Hi, 
Please look at #298

**Comment by nim65s** [comment]
and a release will follow, sorry for the inconvenience

**Comment by nim65s** [comment]
by the way, I think your master is on 2.7.9, because this issue was introduced between 2.7.8 and 2.7.9. This explains why https://github.com/ros/rosdistro/pull/33942 is good

**Comment by v4hn** [comment]
indeed it looks like your PR fixes it. :+1:

**Comment by nim65s** [comment]
Fixed in https://github.com/stack-of-tasks/eigenpy/releases/tag/v2.7.10
