### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/eigenpy#31]
Dear Justin,
Could we make a new release to have the new python fix on the master branch and ready for packaging.
Or do you see a major problem with that ?
All the best,
Olivier.

**Comment by jcarpent** [comment]
I could. I will try to make it today.

**Comment by olivier-stasse** [comment]
Thank you very much.

**Comment by jcarpent** [comment]
The release 1.4.2 is done. The archive is already on robotpkg servers.
I let you update the master of robotpkg to publish this release.
