### ISSUE TITLE
Latest eigenpy binaries for ROS Melodic

### ISSUE THREAD

**Issue by RVSagar** [stack-of-tasks/eigenpy#320]
Hi There,

I wanted to find out whether the latest eigenpy releases will be pushed to the ROS buildfarm for Melodic? I think the latest version as of this post (apt-get install ros-melodic-eigenpy) is 2.7.5. I'm mainly interested because I'm building a Docker container (with the [pinocchio3-preview](https://github.com/stack-of-tasks/pinocchio/tree/pinocchio3-preview) branch) which seems to require 2.7.10.

Thanks for your help and these great packages!

**Comment by wxmerkt** [comment]
Hi @RVSagar 
They have been released to the staging/testing repository yesterday and will be available with the next sync. If you want to use them today, you can switch your apt-list to use `ros-testing`. Hope this helps

**Comment by RVSagar** [comment]
@wxmerkt thanks for the update and options! (didn't know about `ros-testing`)
