### ISSUE TITLE
Segmentation Fault on Import (Probably due to RPATH Setup)

### ISSUE THREAD

**Issue by psclklnk** [stack-of-tasks/eigenpy#322]
Hello everyone,

I currently have an issue using this library (and with that the beautiful pinocchio library) on my M1 Macbook. While the installation via conda works smoothly, I get a segmentation fault as soon as I try to import eigenpy.

My conda setup is nothing really special, I simply ran the following lines to set it and eigenpy up:

```
conda create -n eigenpytest python=3.8
conda install -c conda-forge eigenpy
```

After that, running a simple

```
import eigenpy
```

in the command line python interpreter already leads to the aforementioned segmentation fault. Doing a bit of digging, I realized that eigenpy works like a charm if I build it from source. Digging deeper, I found the following differences between the runtime dependencies of the conda and source-built versions of eigenpy

**Source-Built:**
```
attributes     load path 
               @rpath/libeigenpy.dylib
               @rpath/libboost_python38.dylib
               /usr/lib/libc++.1.dylib
               /usr/lib/libSystem.B.dylib
```

**Conda:**
```
attributes   load path
             @rpath/libeigenpy.dylib
             @rpath/libboost_python38.dylib
             @rpath/libc++.1.dylib
             /usr/lib/libSystem.B.dylib
```

As can be seen, the difference is in the libc++.1.dylib dependency, which is hard-coded to /usr/lib when building from source but rpath-dependent when installed from conda. Checking the rpath setup of the conda version, I found

```
Load command 18
          cmd LC_RPATH
          cmdsize 40
          path @loader_path/../../../ (offset 12)
```

So at this point my knowledge becomes a bit rusty. If I understand correctly, **@loader_path** should translate to the location of the python executable, since it is the loader of the library. Following this logic, I would end up in the miniconda3 directory, where there is no libc++1.dylib present. However, in miniconda3/lib, there is one present. I am also wondering how the conda library would find the libeigenpy.dylib and libboost_python38.dylib in that case.

Could somebody explain the reasoning behind the specific RPATH entry for the eigenpy dynamic library when being loaded from conda?

Unfortunately, my knowledge with adding additional LC_RPATH entries to a **signed** library with install_name_tools is also incomplete, so I could not just add the lib directory of the conda environment to see if that helps. Any tips for this are also very welcome :)

Best regards and thanks in advance
Pascal

**Comment by jcarpent** [comment]
Dear @psclklnk,

Thanks for raising this issue.
Could you provide the result of `conda list` to know precisely your current setup?

When working with conda-forge, you should always enforce the following setting:
```
conda config --add channels conda-forge
conda config --set channel_priority strict
```
Have you done it?

Best,
Justin

PS: on the conda-forge build-farm, it seems there is no falling when testing the import. I hope the previous advises would help.

**Comment by psclklnk** [comment]
Dear @jcarpent ,

regarding the prioritization, I think have the right setup. My .condarc has the following content

```
auto_activate_base: false
channels:
  - conda-forge
  - defaults
channel_priority: strict
```

The output of conda list is

```
boost                     1.78.0           py38hfb399f3_0    conda-forge
boost-cpp                 1.78.0               h1cb353e_1    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.9.14            h4653dfc_0    conda-forge
eigen                     3.4.0                hc021e02_0    conda-forge
eigenpy                   2.7.14           py38h3f0665a_0    conda-forge
icu                       70.1                 h6b3803e_0    conda-forge
libblas                   3.9.0           16_osxarm64_openblas    conda-forge
libcblas                  3.9.0           16_osxarm64_openblas    conda-forge
libcxx                    14.0.6               h2692d47_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           11_3_0_hd922786_25    conda-forge
libgfortran5              11.3.0              hdaf2cc0_25    conda-forge
liblapack                 3.9.0           16_osxarm64_openblas    conda-forge
libopenblas               0.3.21          openmp_hc731615_3    conda-forge
libsqlite                 3.39.3               h76d750c_0    conda-forge
libzlib                   1.2.12               h03a7124_3    conda-forge
llvm-openmp               14.0.4               hd125106_0    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
numpy                     1.23.3           py38h266fe8d_0    conda-forge
openssl                   3.0.5                h03a7124_2    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
python                    3.8.13          hd3575e6_0_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
readline                  8.1.2                h46ed386_0    conda-forge
setuptools                65.3.0             pyhd8ed1ab_1    conda-forge
sqlite                    3.39.3               h2229b38_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
zstd                      1.5.2                h8128057_4    conda-forge
```

Coincidentally, I found an old conda environment which had Pinocchio (and hence eigenpy) installed where it works! Interestingly, it has the same dependency and rpath setup as the eigenpy installation in the failing conda environment. However, it is eigenpy in version 2.7.6 compared to version 2.7.14. So I tried the following in the failing environment

```
conda uninstall eigenpy
conda install eigenpy=2.7.6
```

and suddenly, everything worked like a charm. Do you have an idea why it fails for the 2.7.14 version?

Best
Pascal

**Comment by jcarpent** [comment]
I think the issue is boost-python 1.78 (boost conda package) within conda which has been compiled with clang 13 and is delivered with clang 14. 
We had several discussions on this topic with @traversaro recently. 
@traversaro Do you know when this issue will be solved? Should we update boost 1.78 to use clang 14 directly?

**Comment by psclklnk** [comment]
Ah maybe yes. Maybe I can either confirm or confute the clang 14 assumption to help in fixing this issue for the future. 

Checking the compiler of the conda environment in which I built eigenpy from source (i.e. the one in which it worked with boost 1.78.0), gave me version 14.

**Comment by traversaro** [comment]
> @traversaro Do you know when this issue will be solved? Should we update boost 1.78 to use clang 14 directly?

boost 1.78 build on conda-forge still ue clang 13, and the migration to it (not to mention boost 1.80) is still ongoing: https://conda-forge.org/status/#boost1780 . 

For the time being, the safest solution is to add a `conda_build_config.yaml` file in the recipe directory :

~~~
c_compiler_version:        # [osx]
  - 13                     # [osx]
cxx_compiler_version:      # [osx]
  - 13                     # [osx]
~~~

and re-render. This would avoid the need to manually modify the files as done in https://github.com/conda-forge/eigenpy-feedstock/pull/97/commits/23a66111d26a61719e03b069e21d5b75a09fc9cf .

**Comment by jcarpent** [comment]
Thanks a lot @traversaro for this hint. I've just opened a new PR https://github.com/conda-forge/eigenpy-feedstock/pull/98

**Comment by jcarpent** [comment]
Should be solved now.

**Comment by psclklnk** [comment]
Thanks for the update! I will try it later when I am back at my computer to confirm
