### ISSUE TITLE
Proposal: port StdVectorPythonVisitor from Pinocchio's bindings

### ISSUE THREAD

**Issue by ManifoldFR** [stack-of-tasks/eigenpy#324]
The header is here: https://github.com/stack-of-tasks/pinocchio/blob/devel/bindings/python/utils/std-vector.hpp (or a more recent version).
I recently suggested moving/copying the **`StdVectorPythonVisitor`** template from Pinocchio's bindings upstream to this repo, so that downstream packages don't have to import or copy the header from Pinocchio.

We could also import the **`StdContainerFromPythonList`** template.

What do we think of this ? I could do it if we choose to go ahead with it.

**Comment by jcarpent** [comment]
Please move forward ;)

**Comment by jcarpent** [comment]
Thanks in advance

**Comment by jcarpent** [comment]
Solved via #325.
