### ISSUE TITLE
[2.8.0] bug for Quaternion constructor for strided data

### ISSUE THREAD

**Issue by Arpafaucon** [stack-of-tasks/eigenpy#331]
I noticed a bug when feeding `eigenpy.Quaternion` with a slice of a bigger 2d `numpy` array.

Instead of using the coefficients of the slice to init the Quaternion, it seems `eigenpy` picks those of the contiguous array starting at the first coefficient location (the example below will make this sentence much clearer).

### Clean conda env

spawn a `conda` docker container
```sh
docker run -it continuumio/anaconda3 /bin/bash
```
Inside it
```sh
conda create --name snow python=3.8 numpy ipython
conda activate snow
conda install -c conda-forge eigenpy=2.8.0
ipython
```
In ipython
```py
import eigenpy
import numpy as np

# we (normally) only care about the first column
position = np.array(
    [[0, 0.2, 0.3, 0.4],
     [0,   1,   0,   0],
     [0,   0,   0,   0],
     [1,   0,   0,   0]]
)
print("total array")
print(position)
data_strided = position[:, 0]
print("quaternion data")
print(data_strided)


print("Strided data")
print(data_strided.flags)
# C_CONTIGUOUS : False
# F_CONTIGUOUS : False
# OWNDATA : False
# WRITEABLE : True
# ALIGNED : True
# WRITEBACKIFCOPY : False
q_strided = eigenpy.Quaternion(data_strided)
print(q_strided)
# (x,y,z,w) =   0 0.2 0.3 0.4

print("Contiguous data")
data_compact = np.ascontiguousarray(data_strided)
print(data_compact.flags)
# C_CONTIGUOUS : True
# F_CONTIGUOUS : True
# OWNDATA : True
# WRITEABLE : True
# ALIGNED : True
# WRITEBACKIFCOPY : False
q_compact = eigenpy.Quaternion(data_compact)
print(q_compact)
# (x,y,z,w) = 0 0 0 1
```

looks like we ended up using the coefficient of the first row, though we specified the column as input.

playing with different other versions:
- `2.6.7` works
- `2.7.0` breaks
- `2.7.14` breaks

**Comment by jcarpent** [comment]
@Arpafaucon Thanks for raising this issue.
I've fixed the bug in #332.
I will make a new release after the CI is green.
