### ISSUE TITLE
Pip installation failure on Windows: No matching distribution found for eigenpy

### ISSUE THREAD

**Issue by ducroq** [stack-of-tasks/eigenpy#372]
On windows, python version 3.10:
ERROR: Could not find a version that satisfies the requirement eigenpy (from versions: none)

**Comment by jcarpent** [comment]
Could you switch to Conda instead of pip? We do not yet support eigenpy pip installation on Windows.
@nim65s Do you have a timeline in mind to support this feature via cmeel?

**Comment by nim65s** [comment]
it works on WSL2. I don't have timeline for native windows.

**Comment by ducroq** [comment]
Too bad, but thanks for your fast reply
