### ISSUE TITLE
make VectorXd from list of numbers

### ISSUE THREAD

**Issue by ofloveandhate** [stack-of-tasks/eigenpy#377]
Hi! I'd like to be able to make a vector in eigenpy from a list of numbers, like this:

```
import eigenpy
eigenpy.StdVec_VectorXd([1.,2.,3.])
```

But I get this error message:

```
Boost.Python.ArgumentError: Python argument types in
    StdVec_VectorXd.__init__(StdVec_VectorXd, list)
did not match C++ signature:
    __init__(_object* self, std::__1::vector<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::aligned_allocator<Eigen::Matrix<double, -1, 1, 0, -1, 1>>> other)
    __init__(_object* self, unsigned long size, Eigen::Matrix<double, -1, 1, 0, -1, 1> value)
    __init__(_object*)
```

(really, I'd like to be able to do this with my own numeric types, a la #365, but I'm pretty sure this issue covers custom numeric types, too)

**Comment by ofloveandhate** [comment]
[minieigen](https://github.com/eudoxos/minieigen) has some close code in their file `expose_converters.hpp`, but it's beyond me at the moment to do similar in eigenpy, and i do think it should be in eigenpy rather than in my own library using eigenpy.

**Comment by jcarpent** [comment]
Why do you expect as std::vector out of `StdVec_VectorXd([1.,2.,3.])`?
Do you expect for instance to have and std::vector of 3 elements?

**Comment by ofloveandhate** [comment]
Oh, sorry.  I though I was making a VectorXd.  my mistake.  let me see if I can figure out the correct line of code.

**Comment by ofloveandhate** [comment]
How do I make just a VectorXd in eigenpy?

**Comment by ofloveandhate** [comment]
I would like to be able to write 

```
eigenpy.VectorXd( (1,2,3) )
```

 and get the python version of the Eigen double-precision vector filled with (1.0, 2.0, 3.0).

**Comment by jcarpent** [comment]
Just use Numpy. We don't expose Eigen, but do conversion between Numpy and Eigen::Matrix.
We make this choice as Numpy seems to be the most used linear algebra library in Python.

Internally, EigenPy can share the memory between Python and C++ for efficiency reasons.

**Comment by ofloveandhate** [comment]
ohhhhhhh, rigggghhhht.  i'd like to leave this open while I think, if that's ok.

**Comment by ofloveandhate** [comment]
got it.  so if i want a vector of multiprecision numbers I just do something like

```
a = np.array( [mylibrary.Number(1), mylibrary.Number(2), mylibary.Number(3)] )
```

**Comment by ofloveandhate** [comment]
thank you for your very swift help and patience as i had that realization

**Comment by jcarpent** [comment]
> got it. so if i want a vector of multiprecision numbers I just do something like
> 
> ```
> a = np.array( [mylibrary.Number(1), mylibrary.Number(2), mylibary.Number(3)] )
> ```

Even more simpler:
```python
a  = np.array( [1,2,3], dtype= mylibary.Number)
```
