### ISSUE TITLE
Python bindings changing type depending on imports

### ISSUE THREAD

**Issue by joao-pm-santos96** [stack-of-tasks/eigenpy#392]
Hello all, I've found what I think is an issue that I would like your comments, please.

## Bug description

In a python script, I am trying to import both pinocchio and ompl, which I am able to. The strange behavior that I am witnessing is that, depending on which one I import first, the types of the variables within pinocchio AND ompl change! 

## Expected behavior

I was expecting them to don't change.

## Reproduction steps

When I run 

```py
from os.path import abspath, dirname, join
from sys import argv

from ompl import base, geometric
import pinocchio

# This path refers to Pinocchio source code but you can define your own directory here.
pinocchio_model_dir = join(dirname(dirname(str(abspath(__file__)))), "models")

# You should change here to set up your own URDF file or just pass it as an argument of this example.
urdf_filename = (
    pinocchio_model_dir
    + "/example-robot-data/robots/ur_description/urdf/ur5_robot.urdf"
    if len(argv) < 2
    else argv[1]
)

# Load the urdf model
model = pinocchio.buildModelFromUrdf(urdf_filename)
# print("model name: " + model.name)

# Create data required by the algorithms
data = model.createData()

print("Pinocchio model.names type:", end=" ")
print(type(model.names))
print("")


bounds = base.RealVectorBounds(model.nq)
print("OMPL base.RealVectorBounds.high type:", end=" ")
print(type(bounds.high))
print("")
```

I expected the output to be 

```
Pinocchio model.names type: <class 'pinocchio.pinocchio_pywrap.StdVec_StdString'>

OMPL base.RealVectorBounds.high type: <class 'ompl.util._util.vectorDouble'>
```

Yet the actual output is 

```
Pinocchio model.names type: <class 'ompl.util._util.vectorString'>

OMPL base.RealVectorBounds.high type: <class 'ompl.util._util.vectorDouble'
```

and if switch from 

```py
from ompl import base, geometric
import pinocchio
```

to

```py
import pinocchio
from ompl import base, geometric
```

the output becomes

```
Pinocchio model.names type: <class 'pinocchio.pinocchio_pywrap.StdVec_StdString'>

OMPL base.RealVectorBounds.high type: <class 'pinocchio.pinocchio_pywrap.StdVec_Double'
```

### System

- OS: ubuntu 22.04
- Pinocchio version: 2.6.20

**Comment by jorisv** [comment]
Hi @joao-pm-santos96,

The #393 should fix your issue. Can you try it with ompl ? You will need to rebuild EigenPy and Pinocchio.

**Comment by joao-pm-santos96** [comment]
On eigenpy 3.1.3 I still have the same issue.

**Comment by jorisv** [comment]
@joao-pm-santos96 the modification in EigenPy only affect the vector defined in EigenPy (Eigen matrix vector).
You need to rebuild Pinocchio with the last EigenPy version to modify vector defined in Pinocchio.

I'm going to try to release a new version of Pinocchio soon (tomorrow or on Monday).

**Comment by joao-pm-santos96** [comment]
Hi @jorisv . I've just tested pinocchio 2.6.21 and it seams to be working as expected! Thank you so much!

**Comment by joao-pm-santos96** [comment]
Hello @jorisv , @jcarpent 
Sorry for "re-opening" this, but I've found a similar behavior once again 😢 . Here is a diff of what I've found so far: in GREEN that expected, in RED the type overwrite of OMPL. 

```diff
6,7c6,7
< idx_qs, <class 'ompl.util._util.vectorInt'>
< idx_vs, <class 'ompl.util._util.vectorInt'>
---
> idx_qs, <class 'pinocchio.pinocchio_pywrap.StdVec_Int'>
> idx_vs, <class 'pinocchio.pinocchio_pywrap.StdVec_Int'>
13c13
< names, <class 'ompl.util._util.vectorString'>
---
> names, <class 'pinocchio.pinocchio_pywrap.StdVec_StdString'>
18c18
< nqs, <class 'ompl.util._util.vectorInt'>
---
> nqs, <class 'pinocchio.pinocchio_pywrap.StdVec_Int'>
20,21c20,21
< nvs, <class 'ompl.util._util.vectorInt'>
< parents, <class 'ompl.util._util.vectorSizeT'>
---
> nvs, <class 'pinocchio.pinocchio_pywrap.StdVec_Int'>
> parents, <class 'pinocchio.pinocchio_pywrap.StdVec_Index'>
```

Is there anything on my side that I can do to help?

**Comment by joao-pm-santos96** [comment]
also, the files: 
[no_ompl.txt](https://github.com/stack-of-tasks/eigenpy/files/14220783/no_ompl.txt)
[ompl.txt](https://github.com/stack-of-tasks/eigenpy/files/14220784/ompl.txt)

**Comment by jcarpent** [comment]
The best way would be to import Pinocchio first by doing in the python bindings of ompl `bp::import("pinocchio")`
