### ISSUE TITLE
should not eigenpy install to ~/.local, rather than /usr/local ?

### ISSUE THREAD

**Issue by madjestic** [stack-of-tasks/eigenpy#40]
Hey guys,

I am building eigenpy and having fun debugging why it does not work.  I am running gentoo and it feels like the installation path is sub-optimal.  Is there a reason, why eigenpy needs to be installed to a system path, rather than user home dir, e.g. ~/.local/... ?

Thanks,
V

**Comment by jcarpent** [comment]
How do you install eigenpy: from source directly?
In this case, you can define your CMAKE_INSTALL_PREFIX to point to ~/.local directory.

```
cmake .. -DCMAKE_INSTALL_PREFIX=~/.local 
```

Does it work?

**Comment by madjestic** [comment]
So, I tried editing the `cmake_install.cmake` and replace `set(CMAKE_INSTALL_PREFIX "/usr/local")` with
  `set(CMAKE_INSTALL_PREFIX "~/.local")`, and then run `make install`, but that led to the error:
```
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: ""
CMake Error at cmake_install.cmake:42 (file):
  file INSTALL destination: ~/.local/include/eigenpy is not a directory.


make: *** [Makefile:89: install] Error 1
```
What worked was to have `~/.local/lib64/python3.6/site-packages/eigenpy/eigenpy.so`, together with `/usr/local/lib/libeigenpy.so`

Thanks,
Vlad

**Comment by jcarpent** [comment]
It sounds that ~/.local/include does not exist. You should create this directory I guess.

**Comment by jcarpent** [comment]
@madjestic Does it work?

**Comment by madjestic** [comment]
Thanks!

That worked,
Vlad

**Comment by olivier-stasse** [comment]
Hi Vlad,
Just to inform you that eigenpy is included in a package management system called robotpkg.
This allow us to work with various versions using different OS, compiler, robots.
In order to make sure that everybody can live separetly in the same computer we need to control
the install directory. Installing python packages in .local will be difficult in such situations.

I hope this explain a bit better the rationale behind this choice.
Best,
Olivier.

**Comment by madjestic** [comment]
Hey, Olivier

I understand the rationale behind intent to control installation path, but I don't understand why it has to be a system path by default, rather than local user path.  I will try out the robotpkg, though I am not sure if I like the idea of introducing yet another packaging system on top of what already exists in the system.  Maybe using a  default package manager is better?  But then, of course, somebody needs to create the package.


Thanks, 
Vlad

**Comment by nim65s** [comment]
Hi vlad,

Robotpkg allows us to easily create packages (both source and binaries) for ubuntu (12.04, 14.04, 16.04 & 18.04), Fedora (27 & 28), CentOS 7, Debian 8, NetBSD 8, and a few other but with less support, from a simple Makefile.

This includes support for ROS, and we really need it as we are working on robots which are provided with forks of some core ROS packages.

This explains our packaging process.

Do you have examples of other open sources project that provide a local installation path by default ? 
I'm pretty sure to always have to use something like `cmake -DCMAKE_INSTALL_PREFIX=~/.local ..` or `./configure PREFIX=~/.local` in all the other projects I use, and I think this forces users to understand what they are doing with their prefixes, which is a good idea.
