### ISSUE TITLE
Return np.array over np.matrix for better performance

### ISSUE THREAD

**Issue by jviereck** [stack-of-tasks/eigenpy#41]
Right now eigenpy returns an `np.matrix`. When returning a `np.array`, I manage to get roughly 10x speedup on a simple benchmark. Also, I managed to improve the performance of computing the overall controller.

Therefore, how do you folks feel about returning np.array instead of np.matrix for performance reasons from eigenpy?

Here is the basic benchmark I did:

```
import time
import timeit

oMf = robot.data.oMf
obj = oMf[0]
a = (0., 0., 0.)
%timeit np.array(a)
%timeit np.matrix(a)
%timeit obj.translation
%timeit oMf[0].translation

### Returning np.matrix from eigenpy
#
# 872 ns ± 17.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
# 8.5 µs ± 46.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
# 5.04 µs ± 24.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
# 5.65 µs ± 45.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
#
# ==> Sim + Control: 0.4053959846496582

### Returning np.array from eigenpy

# 793 ns ± 4.81 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
# 8.35 µs ± 155 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
# 353 ns ± 19.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
# 629 ns ± 9.26 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
#
# ==> Sim + Control: 0.2630190849304199
```

**Comment by jcarpent** [comment]
It looks interesting.
Can you provide a whole self-content script?

**Comment by jcarpent** [comment]
The problem is that most of the current scripts using Pinocchio assume np.matrix as return type.
It would be hard to change all the scripts for that.

**Comment by jcarpent** [comment]
What can be done, is to add an option in eigenpy to convert all the Eigen::Matrix as np.array.

**Comment by jcarpent** [comment]
Feel free to open this issue again if needed.

**Comment by jviereck** [comment]
Thanks @jcarpent for implementing this!
