### ISSUE TITLE
Manage boost::variant by reference

### ISSUE THREAD

**Issue by jorisv** [stack-of-tasks/eigenpy#419]
Backport and generalize boost::variant management [from this issue](https://github.com/stack-of-tasks/pinocchio/pull/2119).

User should be able to easily add a new boost::variant type and to get the value inside it by reference.

**Comment by ManifoldFR** [comment]
The idea is having some kind of helper to expose a `boost::variant` type?

**Comment by jcarpent** [comment]
Yes, indeed. The idea will be to have access to a reference of the underlying instance with the right type.

**Comment by jcarpent** [comment]
Solved via #431
