### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/eigenpy#44]
Concerning the following error message, in debug mode:
https://github.com/stack-of-tasks/eigenpy/blob/f567b496decf9a5f82023a76b3f0d5892f490f43/include/eigenpy/details.hpp#L192

When I do SE3 * SE3 object, I get this warning because I guess it tries to find which SE3::operator* to use. In this case, it is not an error message.

Is there any cases where it is a real error ? If my understanding is correct, it is not a failure.

**Comment by jcarpent** [comment]
You're right, this is not a failure, just a test for convertibility.
This was at the beginning a debug feature, outdated now.

I will remove it. Thanks for pointing out this issue.

**Comment by jcarpent** [comment]
Solved by #46.

**Comment by jmirabel** [comment]
Thanks.
