### ISSUE TITLE
Eigen Vector types need to be initialized with transpose operator

### ISSUE THREAD

**Issue by stonneau** [stack-of-tasks/eigenpy#48]
Hi,
after updating eigenpy to the latest devel commit ( https://github.com/stack-of-tasks/eigenpy/commit/b7865b83656f3f1665755427139035d52a020dbd ),

I realized that my previous python scripts needed a small modification to run without failure.

Before, I had a binded c++ method with signature : 

void A(const Eigen::Vector3d&)

for instance called in python with:
bindedA(np.matrix([0.,1.,1.]) )

Now the same method must be called with a transpose to work:

bindedA(np.matrix([0.,1.,1.]).transpose() )

that is not a big issue, but I was just wondering if there was a reason for that and whether it
was achieved on purpose. Thanks

**Comment by jcarpent** [comment]
I realized recently that the condition to allow the conversion between numpy object and Eigen matrices were not correct. I then fixed them.

One of them was about the convention that a vector is either a column or a row vector that both frameworks support. 
In your case, this is this convention that you have to fulfill as Eigen::Vector3d is a column vector.

If a lot of your code is affected, we may add an option to recover the previous behavior (laxist in some sense)

**Comment by stonneau** [comment]
I don't think this is worth it, thanks !
