### ISSUE TITLE
Upcoming ROS Release of eigenpy

### ISSUE THREAD

**Issue by wxmerkt** [stack-of-tasks/eigenpy#49]
As noted in https://github.com/stack-of-tasks/pinocchio/pull/653, we are working on packaging eigenpy and releasing it as binary via the ROS buildfarm, i.e., such that users can install it via `sudo apt install ros-[kinetic/melodic]-eigenpy`. The status of the release pull requests is:

- Kinetic: https://github.com/ros/rosdistro/pull/20115
- Melodic: https://github.com/ros/rosdistro/pull/20114

I will close this issue once the packages are available (~a few weeks).

**Comment by jcarpent** [comment]
@wxmerkt Do you think we can close this issue now?
