### ISSUE TITLE
Bump cmake repo

### ISSUE THREAD

**Issue by jviereck** [stack-of-tasks/eigenpy#50]
When compiling eigenpy on Ubuntu 16.04 for python 3.5, the current repo setup found the libboost-python for python2.7. After bumping the cmake subrepo to the lastest master commit, the cmake found the proper libboost-python for python3.5.

**Comment by nim65s** [comment]
I updated it on the devel branch. But please beware of #35 for python 3.5 on ubuntu 16.04.

**Comment by jcarpent** [comment]
@nim65s You were too fast. Your push is not passing testing. Can you fix it?

**Comment by nim65s** [comment]
Didn't expect that, I will fix it.

**Comment by nim65s** [comment]
fixed: https://travis-ci.org/nim65s/eigenpy/builds/490533063 ; but we'll need to update the cmake submodule once again after the merge of https://github.com/jrl-umi3218/jrl-cmakemodules/pull/186

**Comment by jcarpent** [comment]
@nim65s I've just merged jrl-umi3218/jrl-cmakemodules#186. You can proceed to the synchronization.

**Comment by jcarpent** [comment]
Solved by #51.
