### ISSUE TITLE
Eigenpy on arm64

### ISSUE THREAD

**Issue by MMarcus95** [stack-of-tasks/eigenpy#517]
Hello,
Thanks for developing this useful framework.

Is it possible to install eigenpy on arm64? I cannot find it on http://robotpkg.openrobots.org/packages/debian/pub

**Comment by nim65s** [comment]
Hi @MMarcus95,
arm64 binaries are not available on robotpkg, but they are on conda, nix and pip (the later is a bit outdated, but I hope to be able to fix that by the end of the year)

**Comment by MMarcus95** [comment]
Ok thanks, I'm going try with nix or pip.
