### ISSUE TITLE
git submodules contain SSH-path

### ISSUE THREAD

**Issue by markusgft** [stack-of-tasks/eigenpy#52]
The URL url = git://github.com/jrl-umi3218/jrl-cmakemodules.git
limits accessibility for many users. 
Please apply same modifications as in https://github.com/stack-of-tasks/pinocchio/issues/667

**Comment by jcarpent** [comment]
Yes, sure. I will do that now. Thanks for the quick report.

**Comment by jcarpent** [comment]
Solved by #53.
