### ISSUE TITLE
Binding Eigen special matrices

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/eigenpy#60]
Hi all,

I am wonder it's possible to bind special matrices such as Eigen::DiagonalMatric<double, -1>? For sure, I can transform this matrices in my wrapping code to Eigen::MatrixXd, however, I am looking for a more elegant solution, if it's possible.

**Comment by jcarpent** [comment]
`Eigen::DiagonalMatric<double, -1>`is an expression in Eigen. It would not be useful with NumPy to handle it as such.
