### ISSUE TITLE
eigenpy breaks array reshaping

### ISSUE THREAD

**Issue by rhaschke** [stack-of-tasks/eigenpy#63]
When using eigenpy, flattening of arrays fails:
```python
import numpy
v = numpy.array([1,2,3,4]).reshape(-1,1)  # column vector
print v.flatten().shape  # should result in (4,), but yields (4,1) when using eigenpy
```

**Comment by jcarpent** [comment]
I will have a look at it. Thanks for raising this bug.

**Comment by jcarpent** [comment]
I've tried on my computer, and the bug you mentioned is not occurring. Can you provide me your NumPy version and the eigenpy version you're currently using?

**Comment by rhaschke** [comment]
numpy: 1.13.3
eigenpy: 1.5.1

But, I guess you were able to reproduce the problem?
I can only validate your fix tomorrow... Thanks for the quick response.

**Comment by rhaschke** [comment]
With your fix my particular problem still exists. I have created a minimal example to reproduce the issue:
```python
from __future__ import print_function

import eigenpy
import numpy as np

quat = eigenpy.Quaternion(1,2,3,4)
a = quat.coeffs().T
print(a, a.flatten())

b = np.array([[1.,2.,3.,4.]])
print(b, b.flatten())
```

which yields:
```
[[ 2.  3.  4.  1.]] [[ 2.  3.  4.  1.]]
[[ 1.  2.  3.  4.]] [ 1.  2.  3.  4.]
```
You can see that the `flatten()` on the Eigen matrix doesn't yield a one-dimensional array, but it stays to be a 1xN matrix.

**Comment by rhaschke** [comment]
Using `np.asarray(a).flatten()` as a workaround, my issue is solved now.
When I was prototyping my code two days ago, I didn't notice that eigenpy objects cannot handle `flatten()` in the usual way and that drove me nearly crazy because I got mismatching dimensions all the time...

**Comment by jcarpent** [comment]
You should in fact use those lines:
```
from __future__ import print_function

import eigenpy
eigenpy.switchToNumpyArray() # Allows to convert Eigen::Matrix into np.array objects
import numpy as np

quat = eigenpy.Quaternion(1,2,3,4)
a = quat.coeffs().T
print(a, a.flatten())

b = np.array([[1.,2.,3.,4.]])
print(b, b.flatten())
```

The content summarizes the way it works. Hope it will help you.

**Comment by rhaschke** [comment]
This seems somewhat unintuitive: [flatten()](url) should always return a 1-dimensional `np.array` (because that's the purpose of flatten). The eigenpy array/matrix mode should only effect how generated matrix-like objects are handled, shouldn't it?
Anyway, thanks a lot for the clarification.

**Comment by jmirabel** [comment]
> This seems somewhat unintuitive: flatten() should always return a 1-dimensional

This is a numpy issue:
```python
import numpy
print (numpy.array([[1,2,3,4]]).flatten())
print (numpy.matrix([[1,2,3,4]]).flatten())
```
yields
```
[1 2 3 4]
[[1 2 3 4]]
```

**Comment by rhaschke** [comment]
Ahh, OK! Didn't know. I think, I always used arrays so far...

**Comment by jmirabel** [comment]
And you are right to do so:
> It is no longer recommended to use this class, even for linear algebra. Instead use regular arrays. The class may be removed in the future.


https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html
