### ISSUE TITLE
Writing internal values of eigen bindings

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/eigenpy#65]
I would like to bind Eigen variables where I can read and write internal values, e.g.

```python
# writing internal variables
myBindClass.data[0] = 2
myBindClass.data[:] = np.matrix(np.zeros(3))
```

For that, I used boost python and this is the code:
```cpp
  .add_property("data", bp::make_getter(&myBindClass::data, bp::return_value_policy<bp::return_by_value>()),
                          bp::make_setter(&myBindClass::data));
```

Despite that this c++ code allows me to write the entirely data, it doesn't allow me to write an specific internal data, i.e.

```python
myBindClass.data = np.matrix(np.zeros(3)) # this works
myBindClass.data[0] = 3 # this doesn't work
myBindClass.data[:] = np.matrix(np.zeros(3)) # this doesn't work
myBindClass.data[0:2] = np.matrix(np.zeros(2)) # this doesn't work
```

Is there a solution provided by eigenpy?

**Comment by jcarpent** [comment]
Currently, NumPy and Eigen do not share the memory. We can do that, do you want to implement it? I may guide you.

**Comment by cmastalli** [comment]
I need this feature. Let me know how to do it :)

**Comment by jcarpent** [comment]
OK. I will come back to you soon.

**Comment by nmansard** [comment]
did you have a look at pinocchio data fields? For example the data.Fcrb seems to be what you look at.

**Comment by nmansard** [comment]
https://github.com/stack-of-tasks/pinocchio/blob/8e8f0711b1efa18e8dbc3ee0eea5693cb2cdd2b4/bindings/python/multibody/data.hpp#L80

**Comment by nmansard** [comment]
After discussion with @cmastalli : he reported the problem also raised in pinocchio of writing in a eigen object (for example data.Jcom[0,0] = 0), that is 1) not working and 2) silently failing. @cmastalli will propose a minimal example of how this feature would be used (if available) in Crocoddyl.

**Comment by gabrielebndn** [comment]
I've reopened this issue as I think it is important

**Comment by jcarpent** [comment]
I will close it because it is redundant with #88.
