### ISSUE TITLE
Why are Python and NumPy system include paths?

### ISSUE THREAD

**Issue by wxmerkt** [stack-of-tasks/eigenpy#68]
From MoveIt (https://github.com/ros-planning/moveit/issues/1536):

> Instead upstream relies on pkg-config, but incidentally their pkgconfig file is broken too - it uses -isystem to include numpy which pkg-config --cflags-only-I eigenpy fails to extract.

Indeed, they are currently set as system includes:
https://github.com/stack-of-tasks/eigenpy/blob/aacf9982064140368ebacfcece40db5ed33e3d76/CMakeLists.txt#L53-L55

And when running `pkg-config --cflags-only-I eigenpy`, indeed the NumPy is missing. They do show up on `pkg-config --cflags-only-other eigenpy` though, as expected. 

Is there a specific reason to set them as `SYSTEM`?

Edit: From [CMake docs](https://cmake.org/cmake/help/v3.0/command/include_directories.html):
> If the SYSTEM option is given, the compiler will be told the directories are meant as system include directories on some platforms. Signalling this setting might achieve effects such as the compiler skipping warnings, or these fixed-install system files not being considered in dependency calculations - see compiler docs.

**Comment by jcarpent** [comment]
The main reason is to avoid warnings coming from dependencies when compiling.

**Comment by jcarpent** [comment]
I think I can close this issue. @wxmerkt Feel free to reopen it if needed.
