### ISSUE TITLE
switchToNumpyArray should resemble to default NumPy behaviour

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/eigenpy#70]
A bind Eigen::Vector is converted into a column-Numpy array. This is not the default behaviour of Numpy. I suggest that we should stick to a row vector.

@jcarpent What is your though about it?

**Comment by jcarpent** [comment]
This is already present since EigenPy 1.5.2

**Comment by cmastalli** [comment]
Great! I didn't know it. Thank you for the feedback :)
