### ISSUE TITLE
pkg-config does not contain the correct version

### ISSUE THREAD

**Issue by aelkhour** [stack-of-tasks/eigenpy#8]
I don't know what causes this, but the eigenpy.pc file contains the version 1.2.0-14-g1b20 instead of 1.3.0. @jcarpent Could it be related to 4683053f2016491f40f145e01fb67074cdef3bc6?

**Comment by jcarpent** [comment]
The problem was not coming from 4683053 but it was linked to the tag done with the Github interface which was not annotated. The problem is now fixed.

**Comment by aelkhour** [comment]
Thanks @jcarpent, closing.
