### ISSUE TITLE
Converter from/to std::iterables to boost Python

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/eigenpy#80]
Hi Justin,

I have added this converter inside Crocoddyl (for more details see https://gepgitlab.laas.fr/loco-3d/crocoddyl/blob/cpp_devel/bindings/python/crocoddyl/utils.hpp).

I was thinking that maybe eigenpy is the right place for this code. What do you think? 

If you agree with it, I could create a PR with these modifications.

Carlos

**Comment by cmastalli** [comment]
As far I know, Pinocchio uses the `vector_indexing_suite` from boost python, and it's not exactly what I propose. With my code, we don't to create an new object (i.e. Std_Force). Instead it recreates exactly a python list.

I use those converter for raw and shared_ptr inside Crocoddyl. Independently of EigenPy, Crocoddyl needs this code, and I don't plan to remove it from there. I just thought that it might be useful to replicate the same (or something similar to) the Crocoddyl code.

**Comment by jcarpent** [comment]
This also means that at each time you call the container (list or vector), you then have a conversion. Which is something you want to avoid for performance reasons I would say.

**Comment by cmastalli** [comment]
I agree. However this isn't important in Crocoddyl.

Do you suggest to do not implement this in EigenPy?

**Comment by jcarpent** [comment]
I think it is important. If you want to avoid memory allocation in Python mostly!

**Comment by jcarpent** [comment]
I think we can find a solution avoiding allocation, and doing what you want: behaving as a Python list but without the defect of allocation. Do you get my point?

**Comment by cmastalli** [comment]
It would definitely be great!

**Comment by cmastalli** [comment]
However I'm not sure how this is possible. Just for reference:

 - This is from std::vector to list: https://gepgitlab.laas.fr/loco-3d/crocoddyl/blob/cpp_devel/bindings/python/crocoddyl/utils.hpp#L60

 - And this is from list to std::vector: https://gepgitlab.laas.fr/loco-3d/crocoddyl/blob/cpp_devel/bindings/python/crocoddyl/utils.hpp#L77.

**Comment by jcarpent** [comment]
The code you've copy-pasted is not the most elegant way to do what you need.
They exist a smarter way to proceed. Let's do that later if you don't mind.

**Comment by jcarpent** [comment]
An elegant solution has been proposed in Pinocchio.
