### ISSUE TITLE
issue when calling exposeQuaternion() in several packages

### ISSUE THREAD

**Issue by pFernbach** [stack-of-tasks/eigenpy#83]
Not sure if it's a real issue or if I don't use it correctly, but I have two packages (namely pinocchio and curves) which call     `eigenpy::exposeQuaternion()` in their c++ code for python API. 
The issue is that the python `Quaternion` class only exist in the first package that I import, eg : 

```python
import pinocchio
import curves
pinocchio.Quaternion # ok
curves.Quaternion # do not exist
```

```python
import curves
import pinocchio
pinocchio.Quaternion # do not exist
curves.Quaternion # OK
```

Is there a way to correctly manage this or should I always keep care of the import order ? It could lead to hard to catch error for future users of both packages.

**Comment by jcarpent** [comment]
Please see https://github.com/stack-of-tasks/pinocchio/pull/817 for helps. It has solved the same issue than the one you had.
You then need to update pinocchio to get the latest release.

**Comment by pFernbach** [comment]
Thanks, I'll make the same changes in curves then.
