### ISSUE TITLE
debug cout statements in release 1.5.7

### ISSUE THREAD

**Issue by DiegoAE** [stack-of-tasks/eigenpy#84]
I'was using Pinocchio with an installation of eigenpy (1.5.7) from source, and I got extra verbose output with the following statements:
call: EigenFromPy< Eigen::MatrixBase<MatType> >::convertible
call: EigenFromPy< Eigen::MatrixBase<MatType> >::construct
I found the cout statements in
 https://github.com/stack-of-tasks/eigenpy/blob/42ea7b32def7ecb1e83d3dc0546d3f8d908aaf7a/include/eigenpy/details.hpp#L436
https://github.com/stack-of-tasks/eigenpy/blob/42ea7b32def7ecb1e83d3dc0546d3f8d908aaf7a/include/eigenpy/details.hpp#L444
My guess is that they were intended for debugging purposes.

**Comment by jcarpent** [comment]
Yes, they have been removed in #82. Thanks for raising this issue. Do you need a new release to avoid boring `std::cout`?

**Comment by DiegoAE** [comment]
Thanks for the prompt reply! I removed the cout statements from my repository copy so no need to urgently deliver a new release. However, be aware that the current latest release (1.5.7) has this issue.

**Comment by jcarpent** [comment]
I will provide a release soon to avoid such issues.
I will close the issue now. @DiegoAE Thanks a lot for your comments and feedback.
