### ISSUE TITLE
Where is eigenpyConfig.cmake?

### ISSUE THREAD

**Issue by jwhendy** [stack-of-tasks/eigenpy#86]
Greetings,

I was just building [ros_planning/moveit_ros/planning_interface](https://github.com/ros-planning/moveit/tree/master/moveit_ros/planning_interface) and got this error:

```
-- Could not find the required component 'eigenpy'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "eigenpy" with any
  of the following names:

    eigenpyConfig.cmake
    eigenpy-config.cmake

  Add the installation prefix of "eigenpy" to CMAKE_PREFIX_PATH or set
  "eigenpy_DIR" to a directory containing one of the above files.  If
  "eigenpy" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
```

I have arch linux's eigenpy installed, but indeed I cannot find this file anywhere. I see some discussion on this file at eigenpy #69 and [pinnochio #831](https://github.com/stack-of-tasks/pinocchio/issues/831#issuecomment-511396202), but not how to actually make the magic happen.

I also tried building from git via the instructions on [this comment](https://github.com/stack-of-tasks/pinocchio/issues/831#issuecomment-511692617) (using standard system targets, not the conda ones), but I don't see `eigenpyConfig.cmake` anywhere in the directory tree.

Admittedly I know nothing about cmake, so please forgive if this is some simple setting. Like is the `pkg-config.cmake` the same file, it's just not named definitively??

If it's helpful, [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=eigenpy) is how arch builds the package. If something needs to be changed, I can add a comment or file a report there to make it so.

Thanks for any tips.

**Comment by jwhendy** [comment]
Nevermind... sorry, I should have checked in both locations before posting this. It looks like this is on the radar of moveit planning interface and [this solution](https://github.com/ros-planning/moveit/pull/1550) worked for me.

**Comment by WenqiangX** [comment]
Hi, I met the same problem, could you please tell me how you solve it?
I have read through the "solution" page, but I am not sure what the solution is.

**Comment by nim65s** [comment]
Hi @WenqiangX,
On that issue, the original author is on ArchLinux, and can't find `eigenpyConfig.cmake`. If eigenpy is installed with AUR, this file is in `/usr/lib/cmake/eigenpy`

```bash
╰─>$ pacman -Ql eigenpy | grep eigenpyConfig.cmake
eigenpy /usr/lib/cmake/eigenpy/eigenpyConfig.cmake
```

Can you check that you have this file ? According to [CMake documentation](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure), this correspond to the first search path on unix: `<prefix>/(lib/<arch>|lib*|share)/cmake/<name>*/` for the `/usr` prefix, so if you have it here, you shouldn't see this message.

**Comment by jwhendy** [comment]
@WenqiangX sorry, it's been so long I don't recall what I meant by that link above anymore. I almost wonder if the "solution" was more like it not being a ROS package so ROS wasn't looking for that `.cmake` file, though I can confirm that I also have the file in the location showsn by @nim65s .

**Comment by WenqiangX** [comment]
Thanks for your responses. 
Due to network issue, I cannot make the ubuntu `apt` install successful.
I tried `dpkg -i` install with deb package I download directly from the site. But the file is not there.
In the end, I actually make it work with moveit by `conda install` eigenpy. 
Though the moveit is compiled with /usr/bin/python3, I create a conda environment with exact same version of the /usr/bin/python3, and conda install the  eigenpy, and then the error is gone.

Thank you guys anyway!

**Comment by jwhendy** [comment]
@WenqiangX Ah, you're on Ubuntu. Looking at [their instructions](https://github.com/stack-of-tasks/eigenpy) and [repo](http://robotpkg.openrobots.org/packages/debian/pub/dists/bionic/robotpkg/binary-amd64/), I downloaded `robotpkg-py36-eigenpy_2.4.0_amd64.deb` manually.

```
$ dpkg -c robotpkg-py36-eigenpy_2.4.0_amd64.deb | grep cmake
drwxr-xr-x rbulk/robots      0 2020-06-26 10:01 ./opt/openrobots/lib/cmake/
drwxr-xr-x rbulk/robots      0 2020-06-26 10:01 ./opt/openrobots/lib/cmake/eigenpy/
-rw-r--r-- rbulk/robots   4716 2020-06-26 09:41 ./opt/openrobots/lib/cmake/eigenpy/eigenpyConfig.cmake
-rw-r--r-- rbulk/robots   1607 2020-06-26 09:41 ./opt/openrobots/lib/cmake/eigenpy/eigenpyConfigVersion.cmake
-rw-r--r-- rbulk/robots    925 2020-06-26 09:41 ./opt/openrobots/lib/cmake/eigenpy/eigenpyTargets-release.cmake
-rw-r--r-- rbulk/robots   3585 2020-06-26 09:41 ./opt/openrobots/lib/cmake/eigenpy/eigenpyTargets.cmake
```

It looks like it should be there? Or did I examine the wrong package?

**Comment by nim65s** [comment]
yes, with robotpkg, to let CMake find `/opt/openrobots/lib/cmake/eigenpy/eigenpyConfig.cmake`, you need `export CMAKE_PREFIX_PATH=/opt/openrobots`

**Comment by nim65s** [comment]
for Ubuntu, instructions to use robotpkg binary apt repository are provided here: https://stack-of-tasks.github.io/pinocchio/download.html

**Comment by WenqiangX** [comment]
Thanks again for your help!
