### ISSUE TITLE
Timeline for using np.array by default.

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/eigenpy#87]
Let's open the discussion to decide a timeline for using numpy arrays by default, instead of numpy matrices.

**Comment by cmastalli** [comment]
I vote for the beginning of the next year. So we give a couple of month to everyone adapt their code.

**Comment by nim65s** [comment]
Does this change in defaults settings means that we have anything to adapt ?

**Comment by jmirabel** [comment]
Arrays always do coefficient-wise operations while matrices do not. The most annoying difference is for the operator \*.

**Comment by nim65s** [comment]
ok, thanks

**Comment by jmirabel** [comment]
I think `Array @ Array` does the same thing as `Matrix * Matrix`.

For a smooth change, the best idea I have is to echo a warning the first time an object of type Matrix is returned, only if `eigenpy.switchToNumpyMatrix()` has not been called explicitly.

It is easy to implement and it forces people using matrices to explicitly say they want matrices. 3 months after the release of this warning, I suggest to release a new version of EigenPy, increasing the major number.

**Comment by nmansard** [comment]
The problem of Array@Array is that it breaks the compatibility with 
Python 2.

I agree with your last comment: 3 months after the release of the 
warning, we can change the default behavior of EigenPy (knowing that 
people that are late can keep the previous behavior 
|eigenpy.switchToNumpyMatrix()|).

**Comment by jcarpent** [comment]
Concerning Python2, we won't support it after January 1, 2020 (https://pythonclock.org/).

**Comment by proyan** [comment]
> I vote for the beginning of the next year. So we give a couple of month to everyone adapt their code.

If we want people to adapt their code, the warnings should be issued from now. Then from January, we can move to np.array completely.

**Comment by jmirabel** [comment]
@proyan that's what I suggested.

**Comment by jcarpent** [comment]
Solved by #89. I will provide a new release soon.

**Comment by nim65s** [comment]
I'll wait for this new source release, and after that I will launch the binary releases (eigenpy & pinocchio) on robotpkg

**Comment by jmirabel** [comment]
Time is up !

**Comment by jmirabel** [comment]
Should we change the default ?

**Comment by wxmerkt** [comment]
Happy to change the default for array/matrix. However, we should not change the default for Python2/3 as Python2 will be supported on LTS platforms until they reach their EOL.

**Comment by gabrielebndn** [comment]
I would say that we should wait at least until https://github.com/stack-of-tasks/pinocchio/issues/1026 is solved

**Comment by jcarpent** [comment]
Solved by #150.
