### ISSUE TITLE
Generate and install CMake config

### ISSUE THREAD

**Issue by wxmerkt** [stack-of-tasks/eigenpy#98]
Following https://github.com/jrl-umi3218/jrl-cmakemodules/issues/247, can we please add the necessary features to generate and install the cmake config such that the only requirements to use eigenpy reduce to:

```cmake
find_package(eigenpy REQUIRED)
```

And can we please tag a release using the latest two PRs and this CMake configuration.

(I tried it following the comment in https://github.com/jrl-umi3218/jrl-cmakemodules/issues/247, but didn't get it to install yet)

**Comment by jcarpent** [comment]
Solved by #132.
